"""Rebuild the standalone reference from its own canonical sources."""
from pathlib import Path
import json, html, subprocess
import markdown
ROOT=Path(__file__).resolve().parents[1]
subprocess.run(['node','tools/build-tokens.cjs'],cwd=ROOT,check=True)
data=json.loads((ROOT/'tokens/crystal.json').read_text())
(ROOT/'assets/tokens.js').write_text('window.CRYSTAL_TOKENS = '+json.dumps(data,separators=(',',':'))+';\n')
subprocess.run(['node','-e',"const f=require('fs'),v=require('vm');const c={window:{}};v.createContext(c);for(const p of ['assets/tokens.js','assets/crystal.js'])v.runInContext(f.readFileSync(p,'utf8'),c);f.writeFileSync('assets/crystal-theme.css',c.window.Crystal.exportCSS());"],cwd=ROOT,check=True)
nav=[('principles','Foundations'),('colors','Color'),('materials','Materials'),('components','Components'),('motion','Motion'),('motion-components','Component motion'),('accessibility','Accessibility'),('adoption','Adoption')]
for p in (ROOT/'docs').glob('*.md'):
    title=p.read_text().splitlines()[0].removeprefix('# ')
    content=markdown.markdown(p.read_text(),extensions=['tables','fenced_code','toc'])
    links=''.join(f'<a href="{name}.html"'+(' aria-current="page"' if p.stem==name else '')+f'>{label}</a>' for name,label in nav)
    page=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light dark"><title>{html.escape(title)} · Crystal</title><link rel="icon" href="../assets/icon.svg" type="image/svg+xml"><link rel="stylesheet" href="../assets/crystal-theme.css"><link rel="stylesheet" href="../assets/crystal.css"><link rel="stylesheet" href="../assets/site.css"><link rel="stylesheet" href="../assets/motion.css"><script src="../assets/tokens.js" defer></script><script src="../assets/crystal.js" defer></script><script src="../assets/docs.js" defer></script><style>@layer crystal.base {{.doc-layout{{display:grid;grid-template-columns:170px minmax(0,1fr);gap:48px;padding:42px 0}}.doc-nav{{display:flex;flex-direction:column;gap:7px;align-self:start;position:sticky;top:24px}}.doc-nav a{{padding:9px 12px;border-radius:10px;text-decoration:none;font-size:14px}}.doc-nav a[aria-current]{{background:var(--cr-primary-soft);color:var(--cr-on-primary-soft);font-weight:800}}.doc-body{{max-width:920px;min-width:0}}.doc-body h1{{font-size:38px}}.doc-body h2{{font-size:25px;margin-top:36px}}.doc-body p,.doc-body li{{font-size:15px;line-height:1.8;max-width:78ch}}.doc-body table{{display:block;overflow:auto;border-collapse:collapse;font-size:13px;margin:22px 0;max-width:100%}}.doc-body td,.doc-body th{{border:1px solid var(--cr-edge);padding:12px;text-align:left;min-width:130px}}.doc-body th{{background:var(--cr-primary-soft);color:var(--cr-on-primary-soft)}}.doc-body td{{background:var(--cr-surface)}}@media(max-width:700px){{.doc-layout{{display:block;padding-top:24px}}.doc-nav{{position:static;flex-direction:row;overflow:auto;margin-bottom:30px;gap:5px}}.doc-nav a{{white-space:nowrap}}.doc-body h1{{font-size:30px}}}}}}</style><link rel="stylesheet" href="../assets/controls.css?v=pill-focus-2"><script src="../assets/controls.js?v=pill-focus-2" defer></script></head><body><a class="skip" href="#main">Skip to specification</a><div class="shell"><header class="site-header"><a class="wordmark" href="../index.html" aria-label="Crystal design system"><span class="mark" aria-hidden="true"><svg aria-hidden="true" focusable="false" viewBox="0 0 24 24"><use href="../assets/icons.svg#crystal"/></svg></span>crystal <small>Design system</small></a><nav class="site-nav" aria-label="Main"><a href="../index.html#playground">Playground</a><a href="../index.html#foundations">Foundations</a><a href="../index.html#components">Components</a><a href="../motion.html">Motion</a><a href="../docs/principles.html" aria-current="true">Specification</a><a href="../validation/report.html">Verification</a></nav></header><div class="doc-layout"><nav class="doc-nav" aria-label="Specifications">{links}</nav><main id="main" class="doc-body">{content}</main></div><footer class="site-footer"><p>Crystal 1.0 · Editable specification</p><a href="{p.name}">Markdown source</a></footer></div></body></html>'''
    p.with_suffix('.html').write_text(page)
print('Built browser token data, default CSS and eight specification pages.')
